### ISSUE TITLE
English translation of Germany Chapter landing page

### ISSUE THREAD

**Issue by dansecops** [OWASP/www-chapter-germany#10]
**Issue 1 -** Landing page out of date, info from 2019: Germany Chapter Landing page is out of date and references information from 2019. This needs to be revised for 2021, which Stammtische are active and who are "Vorsitzende" of each Stammtisch. Same applies for "Konferenz" and "Treffen" section, including adding any references to the German OWASP day 2021 as soon as they are available.

**Issue 2** - The current page overview gives preference for chapter board members instead of Stammtische information. However, more important than the chapter board members would be the reference for each Stammtisch. Currently, this information is quite difficult to find via the "Treffen" tab. 
See [SCREENSHOT](https://user-images.githubusercontent.com/4130769/103318823-7e6a2e80-4a27-11eb-9122-601d19f68354.png)

**Issue 3** Also, may be helpful to provide an English translation / section of the Germany Chapter homepage, as some Stammtische are also run in English (at least partly).  

**Issue 4** Add "press" section (?) or remove if not needed.

**Issue 5** Stammtisch guidance: If possible, please add any helpful guidance on how to establish and run a local Stammtisch 

**Issue 6:** Include more information about our inherently German OWASP projects like Juice Shop :)

**Comment by drwetter** [comment]
For English (press 3, errr.. I mean your point 3): IIRC we decided against English a while back. That was before the pandemic. Don't know whether this changes anything in the long run, as the pandemic is soon over \#LOL. If you want to get this changed, propose something and best is if you give a hand. As you realized yourself even the German content leaves room for some improvements.

In general I believe it would be better to file one issue in one issue. That way discussion and addressing each one would be easier.

**Comment by dansecops** [comment]
@drwetter will open several new issues for the other www-chapter-germany overview page changes, excluding the English translation. 

As for some Stammtische have been bilingual in the past (like FFM) and also the the page description, it can be difficult for non-german speakers to navigate through the www-chapter-overview page to find the right Stammtisch information. 

Hence, I'd suggest at least include a small summary in English of the www-chapter-overview index page, including:
- Overview of OWASP Germany Chapter
- translation of what a "Stammtisch" means in the context of OWASP Chapter Germany (and where the work comes from)
- Information which Stammtische also welcome non-German (i.e. English) speakers 
- translation of FAQ for Stammtisch attendees, particularly in terms of requirements for presentations at OWASP Stammtische

Happy to give a hand for translation if we agree with the chapter leads & board members to change the OWASP Germany Chapter landing page to include at least a partial translation in English as mentioned above.

@tglemser @bkimminich @drwetter
