### ISSUE TITLE
Update der Germany Chapter Germany Überssichtseite

### ISSUE THREAD

**Issue by dansecops** [OWASP/www-chapter-germany#11]
Die Übersichtsseite des Chapters ist vom Stand 2019. Diese sollte für 2021 überarbeitet werden. Dazu gehört:

- welche Stammtische aktiv sind und wer "Vorsitzender" des jeweiligen Stammtisches ist.
- Update der Rubriken "Konferenz" und "Treffen" auf aktuellen Stand 2021, inkl. info zum German OWASP Day 2021 sobald verfügbar
- Abschnitt "Presse" hinzufügen (?) oder entfernen, falls nicht benötigt
- Hinzufügen für Anleitungen für Veranstaltung von lokalen Stammtisches (ggf. mit Verweis auf verfügbares [OWASP Material](https://github.com/OWASP/www-committee-chapter/tree/master/resources)
- Verweis auf "deutsche" OWASP Projekte wie bspw. Juice Shop

**Comment by bkimminich** [comment]
Der letzte Punkt ist doch durch den "Projekte"-Tab auf der Seite eigentlich abgedeckt. Oder was schwebte dir da vor? Wir könnte das ein bisschen aufrüschen mit Info wer an diesen Projekten mitwirkt vom German Chapter und evtl. jeweils einen Mini Salespitch je Projekt hinzufügen.

**Comment by dansecops** [comment]
Bezüglich deutsche Projekte - Ja, der Verweis auf deutsche OWASP Projekte ist abgedeckt, aber zusätzliche Info wer diese Projekte vom German Chapter initiiert hat, die Contributors sowie eine kurze Beschreibung (Mini-Pitch) auf deutsch für jedes Projekt wäre hilfreich.

**Comment by bkimminich** [comment]
Die Projektseite kann ich nächste Woche mal ein bisschen aufhübschen.

**Comment by bkimminich** [comment]
Ich hab mal einen 1. Vorschlag für die Projektseite gemacht. Im Grunde sind nur Maturity-Icons, GitHub Badges und eine abgespaltene Sektion für Beteiligungen, die keine Projekte sind, hinzugekommen. Und ich habe die Liste nach Maturity+Sternen sortiert.

Meiner Ansicht nach überfrachten wir die Seite, wenn wir hier noch Kurz-Infos oder Namen der Beteiligten aufführen würden. Und es wäre zudem wieder eine Redundanz, die irgendwer nachhalten muss. Jetzt wäre das nur der Maturity-Level und die gelisteten Projekte an sich. Da würde ich genügend Eigeninteresse der Beteiligten voraussetzen, dass sie ihre Leistungen auf der Liste richtig repräsentiert sehen wollen.

Wie seht ihr anderen das?

**Comment by dansecops** [comment]
Super, danke. Ich werde den PR im laufe der kommenden Tage reviewen. Wie du sagst, müssen wir eine Balance finden für Germany Chapter relevante Infos sowie für Projektinformation die auf anderen OWASP Seiten bereits stehen und ggf. nachgehalten  werden müssen.
