### ISSUE TITLE
Subdirs und Fehler

### ISSUE THREAD

**Issue by drwetter** [OWASP/www-chapter-germany#2]
Moin,

ich habe mal versucht für verschiedene Themen Verzeichnisse anzulegen.

Beim Push habe ich eine Fehlermeldung bekommen, mit der ich nichts anfangen kann:

```
The page build failed for the `master` branch with the following error:

A file was included in `/_layouts/col-sidebar.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#file-is-a-symlink.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

```

``/_layouts/col-sidebar.html`` find ich gar nicht im Repo. Stimmt da was mit Jekyll nicht?

Dirk

**Comment by bkimminich** [comment]
Das äußere Layout und alles drumrum kommt von https://github.com/OWASP/www--site-theme

**Comment by drwetter** [comment]
okay, danke. 

Trotzdem werde ich nicht so klug aus der Fehlermeldung. Muss ich das absolut oder mit ``../`` referenzieren?

**Comment by bkimminich** [comment]
¯\_(ツ)_/¯
Keine Ahnung, ich bin kein Jekyll-Profi. Wenn man nur die vorgesehene Struktur nutzt, klappt alles Bombe... ;-)

**Comment by drwetter** [comment]
see also https://github.com/OWASP/www--site-theme/issues/14

**Comment by bkimminich** [comment]
Die Unterseiten sind bei Direkt-Aufruf aktuell komplett "im Dutt"... z.B. https://www2.owasp.org/www-chapter-germany/stammtische

Ich glaube so funktioniert das nicht wirklich, kenne jetzt aber auch keine Lösung ("kein Jekyll-Profi") ...

**Comment by drwetter** [comment]
Ja, ich wollte da die Tage noch Mal dran. Harold hatte mir n Tipp gegeben.
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by bkimminich** [comment]
Klappt jetzt, daher mach ich das Ticket zu.
